config/routes.rb
require "monban/constraints/signed_in"
require "monban/constraints/signed_out"
require 'resque/server'

Rails.application.routes.draw do
  constraints Monban::Constraints::SignedOut.new do
    root to: "homes#show"
  end

  constraints Monban::Constraints::SignedIn.new do
    root to: "dashboards#show"
  end

  constraints ->(_request) { Rails.env.development? } do
    mount Resque::Server, at: '/jobs'
  end

  # get "/" => "homes#show" # same as above, but above is preferred

  resource :session, only: [:new, :create, :destroy]

  resource :search, only: %i(show)

  resources :recipes, only: [:show] do
    member do
      post "like" => "likes#create"
      post "unlike" => "likes#destroy"
    end

    member do
      post "bookmark" => "bookmarks#create"
      post "unbookmark" => "bookmarks#destroy"
    end

    resources :comments, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create, :show] do
    member do
      post "follow" => "follows#create"
      post "unfollow" => "follows#destroy"
    end
  end

  namespace :my do
    resources :recipes, only: %i(new create edit destroy update)
    resources :users, only: [:edit, :update]
  end

  namespace :api do
    resources :recipes, only: %i(index create destroy)
    resources :users, only: %i(create) do
      member do
        post "follow" => "follows#create"
        post "unfollow" => "follows#destroy"
      end
    end
    resource :credentials, only: %i(create)
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_attached_file :image, styles: {medium: "300x300>", thumb: "100x100>"}, default_url: "/images/normal/grumpy_cat.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :title, presence: true
  validates :ingredients, length: {minimum: 1}
  validates :steps, length: {minimum: 1}

  has_many :ingredients, dependent: :destroy
  has_many :steps, dependent: :destroy

  # has_many :recipe_comment_relationship, class_name: "Comment", dependent: :destroy
  has_one :search_index, dependent: :destroy
  has_many :comments, dependent: :destroy #, through: :recipe_comment_relationship
  has_many :bookmarks, dependent: :destroy
  has_many :user_activities, as: :target, dependent: :destroy

  # has_many :liked_recipe_relationships,
  #          class_name: "Like"

  belongs_to :user
  # , through: :liked_recipe_relationshipsx

  accepts_nested_attributes_for :ingredients,
                                allow_destroy: true,
                                reject_if: :all_blank
  accepts_nested_attributes_for :steps,
                                allow_destroy: true,
                                reject_if: :all_blank

  belongs_to :user

  delegate :username, to: :user

  scope :latest, -> { order(created_at: :desc) }

  # SEARCH_QUERY_MAP = {
  #   "title","ingredients"
  # }
  # scope :search_ingredients, ->(query:) { where("title LIKE ?", "%#{query}%") }

  def self.search2(query)
    results1 = Recipe.where("title LIKE ?", "%#{query}%")

    results2 = Recipe.all.map do |recipe|
      r = recipe.ingredients.where("name LIKE ?", "%#{query}%")
      if r.count > 0
        recipe
      end
    end
    (results1 + results2).uniq.compact

  end
end

app/controllers/api/recipes_controller.rb
class Api::RecipesController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :require_access_token, except: :index

  PER_PAGE_NUMBER = 5.freeze

  def index
    recipes = Recipe.page(page_number).per(PER_PAGE_NUMBER)
    render json: recipes
  end

  def create
    recipe = RecipePublishing.new(user: current_user, recipe_params: recipe_params).run
    if recipe.persisted?
      render json: recipe, status: :ok
    else
      render json: recipe, status: :bad_request
    end
  end

  def destroy
    require_access_token
    recipe = find_recipe

    if recipe
      recipe.destroy
      render json: {}, status: :ok
    else
      render json: {}, status: :bad_request
    end
  end

  private

  def page_number
    params[:page] || 1
  end

  def find_recipe
    recipe = @current_user.recipes.find_by(id: params[:id])
    return recipe
  end

  def recipe_params
    params.require(:recipe)
      .permit(:title,
              :description,
              :image,
              ingredients_attributes: [:id, :name, :_destroy],
              steps_attributes: [:id, :name, :image, :_destroy])
  end

end

app/controllers/my/recipes_controller.rb
class My::RecipesController < My::BaseController
  # TODO: extract to base controller

  def new
    @recipe = Recipe.new #(ingredients: [Ingredient.new])
  end

  def create
    @recipe = RecipePublishing.new(user: current_user, recipe_params: recipe_params).run #current_user.recipes.build(recipe_params)
    if @recipe.persisted?
      redirect_to @recipe
    else
      render :edit
    end
  end

  def edit
    @recipe = find_recipe
  end

  def destroy
    recipe = find_recipe
    recipe.destroy
    redirect_to root_path
  end

  def update
    recipe = RecipeUpdater.new(recipe: find_recipe, recipe_params: recipe_params).run

    if recipe.persisted?
      redirect_to recipe, notice: t(".updated")
    else

    end
  end

  def find_recipe
    current_user.recipes.find(params[:id])
  end

  private
  def recipe_params
    params.require(:recipe)
      .permit(:title,
              :description,
              :image,
              ingredients_attributes: [:id, :name, :_destroy],
              steps_attributes: [:id, :name, :image, :_destroy])
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def show
    @recipe = Recipe.find (params[:id])
  end
end

app/helpers/recipe_helper.rb
module RecipeHelper
  def like_button(recipe)
    if current_user.likes?(recipe)
      button_to t("unlike"), [:unlike, recipe]
    else
      button_to t("like"), [:like, recipe]
    end
  end

  def bookmark_button(recipe)
    if current_user.bookmarks?(recipe)
      button_to t("unbookmark"), [:unbookmark, recipe]
    else
      button_to t("bookmark"), [:bookmark, recipe]
    end
  end

end

app/views/recipes/_comment_fields.html.erb
<div>
  <%= form.label :new_comment %>
  <%= form.text_field :text %>
</div>

app/views/recipes/_comments.html.erb
<h2>Comments</h2>
<ol>
  <% recipe.comments.each do |comment| %>
      <li>
        <%= "#{comment.text} by #{comment.user.email}" %>
      </li>
      <% if current_user.owns?(comment) %>
          <%= link_to t(".delete_comment"), [recipe, comment], method: :delete %>

      <% end %>
  <% end %>
</ol>

app/views/recipes/_controls.html.erb
<div>
  <%= link_to t(".edit"), edit_my_recipe_path(recipe) %>
  <%= link_to t(".delete"), [:my, recipe], method: :delete, date: {confirm: t(".confirm_delete")} %>
</div>

app/views/recipes/_ingredients.html.erb
<h2>Ingredients</h2>
<ul>
  <% recipe.ingredients.each do |ingredient| %>
      <li>
        <%= ingredient.name %>
      </li>
  <% end %>
</ul>

app/views/recipes/_recipe.html.erb
<div class="recipe">
  <%= link_to recipe.title, recipe %>

</div>

app/views/recipes/_steps.html.erb
<h2>Steps</h2>
<ol>
  <% recipe.steps.each do |step| %>
      <li>
        <%= step.name %>
        <%= image_tag step.image.url(:thumb) %>
      </li>
  <% end %>
</ol>

app/views/recipes/edit.html.erb
<%= form_for @recipe do |form| %>

    <div>
      <%= form.label :title %>
      <%= form.text_field :title, required: true %>
    </div>

    <div>
      <%= form.label :description %>
      <%= form.text_field :description %>
    </div>
    <div>
      <%= form.submit "Submit" %>
    </div>
<% end %>

app/views/recipes/show.html.erb
<%= image_tag @recipe.image.url(:medium) %>

<h1>
  <%= @recipe.title %>
</h1>

comment count:
<%= @recipe.comments_count%>

<%= like_button @recipe %>
<%= bookmark_button @recipe %>

<% if @recipe.description.present? %>
    <p><%= @recipe.description %></p>
<% end %>

<%= link_to @recipe.username, @recipe.user %>

<%= render "ingredients", recipe: @recipe %>
<%= render "steps", recipe: @recipe %>
<%= render "comments", recipe: @recipe %>

<%= form_for [@recipe, @recipe.comments.new] do |form| %>
    <%= render "comment_fields", form: form %>

    <div>
      <%= form.submit t(".comment") %>
    </div>
<% end %>
<br>
<% if current_user.owns?(@recipe) %>
    <%= render "controls", recipe: @recipe %>
<% end %>